# Generated by Django 2.2.5 on 2020-10-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0008_quiztaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, help_text='Selecting this will deactivate active events'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='value',
            field=models.IntegerField(default=1, help_text='How many points this question is worth'),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
