# Generated by Django 2.2.5 on 2020-10-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0008_quiztaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
