# Generated by Django 2.2.5 on 2020-10-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0009_auto_20201030_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='quizbank',
            name='deleted',
        ),
    ]
