# Generated by Django 2.2.5 on 2020-10-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0010_auto_20201030_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='image',
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorestapp.Event'),
        ),
        migrations.AlterField(
            model_name='quiztaker',
            name='quiz_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangorestapp.QuizBank'),
        ),
    ]
