# Generated by Django 2.2.5 on 2020-10-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0011_auto_20201030_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='value',
        ),
    ]
