# Generated by Django 2.2.5 on 2020-10-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0012_remove_questionbank_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbankanswer',
            options={'ordering': ['?'], 'verbose_name_plural': 'question bank answers'},
        ),
    ]
