# Generated by Django 2.2.5 on 2020-10-31 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0013_auto_20201030_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.today),
            preserve_default=False,
        ),
    ]
