# Generated by Django 2.2.5 on 2020-11-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0014_quiztaker_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizbank',
            name='timer',
        ),
    ]
