# Generated by Django 2.2.5 on 2020-11-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0015_remove_quizbank_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiztaker',
            old_name='created_at',
            new_name='submit_date',
        ),
    ]
