# Generated by Django 2.2.5 on 2020-11-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0016_auto_20201031_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='info_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
